### ISSUE TITLE
Listening to clientcreated

### ISSUE THREAD

**Issue by fabiokr** [cloudflare/webcm#102]
I was trying to listen to the `clientcreated` event with `manager.addEventListener('clientcreated', callback)`, but that was not triggering anything. 

While debugging the webcm code, I noticed that [here](https://github.com/cloudflare/webcm/blob/main/lib/server.ts#L116), if there is no listener to the `request` event, it just returns, so it never reaches the [next block](https://github.com/cloudflare/webcm/blob/main/lib/server.ts#L119-L129), never triggering the `clientcreated` callback.

Is that intentional for some reason?

cc/ @simonabadoiu @bjesus

**Comment by fabiokr** [comment]
Also related to this, it sounds like this commit changed the code to use page vars to store configuration instead of cookies https://github.com/cloudflare/webcm/commit/393ed9b222dfa0210c0a77be6218e2072a691b60

But then in here, it is still looking the cookies, as as it is never there, it always triggers https://github.com/cloudflare/webcm/blob/main/lib/server.ts#L119

**Comment by bjesus** [comment]
The decision was the `clientcreated` is called the first time _any other event_  is called. So for example you should have a `pageview` listener, and then the `clientcreated` should be triggered just before it

**Comment by bjesus** [comment]
the main thing we want to avoid is letting MCs running code on pages where the MC wasn't meant to be loaded
