### ISSUE TITLE
Detaching on empty listeners

### ISSUE THREAD

**Issue by fabiokr** [cloudflare/webcm#85]
In [here](https://github.com/cloudflare/webcm/blob/unstable/lib/client.ts#L112), if you called `detachListener` before something was actually attached, it will fail with `TypeError: Cannot read properties of undefined (reading 'indexOf')`. 

That should be fixed to something like `const eventIndex = this.webcmPrefs.listeners[component] && this.webcmPrefs.listeners[component].indexOf(event)`.

**Comment by simonabadoiu** [comment]
Fixed
