### ISSUE TITLE
Referer issue

### ISSUE THREAD

**Issue by fabiokr** [cloudflare/webcm#96]
While testing after https://github.com/cloudflare/webcm/pull/95, I noticed that the `client.referer` values are incorrect. There client referer is set from the request header here `https://github.com/cloudflare/webcm/blob/unstable/lib/client.ts#L141`. `pageview` is sent from the context of the current page, so the `referer` headers ends up always being the current url, not the actual referer url. 

The fix is likely to be sending an additional header with the current page referer from `document.referrer` on the browser side.

**Comment by bjesus** [comment]
Can you check if it works fine for you with this PR? https://github.com/cloudflare/webcm/pull/97

**Comment by fabiokr** [comment]
> Can you check if it works fine for you with this PR? #97

Yep, confirmed that fixes it, thanks!
